export const sidebarLinks = [
  {
    label: "Stats",
    url: "/dashboard/stats",
    roles: ["ADMIN_ADMIN", "ADMIN_MEMBER"],
    noSidebar: false,
    currTab: 0,
    isTab: true,
  },
  {
    label: "Seekers",
    url: "/dashboard/seekers",
    roles: ["ADMIN_ADMIN", "ADMIN_MEMBER"],
    noSidebar: false,
    currTab: 1,
    isTab: true,
  },
  {
    label: "Solvers",
    url: "/dashboard/solvers",
    roles: ["ADMIN_ADMIN", "ADMIN_MEMBER"],
    noSidebar: false,
    currTab: 2,
    isTab: true,
  },
  {
    label: "Programs",
    url: "/dashboard/programs",
    roles: ["ADMIN_ADMIN", "ADMIN_MEMBER"],
    noSidebar: false,
    currTab: 3,
    isTab: true,
  },
  {
    label: "Subscribers",
    url: "/dashboard/subscribers",
    roles: ["ADMIN_ADMIN", "ADMIN_MEMBER"],
    noSidebar: false,
    currTab: 4,
    isTab: true,
  },
  {
    label: "Manage members",
    url: "/dashboard/manage-team",
    roles: ["ADMIN_ADMIN"],
    noSidebar: false,
    currTab: 5,
    isTab: true,
  },
];
